import Config

# Configure your database
config :bullet, Bullet.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: String.to_integer(System.get_env("DB_PORT", "5439")),
  database: System.get_env("DB_NAME", "bullet_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :bullet, BulletWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "U2S1jEE3eHIZQaTaLxO8WOV0rqGLQKubf8WBOEWlLdvSk89KTRpYMlEPEtevR5F9",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:bullet, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:bullet, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :bullet, BulletWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/bullet_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :bullet, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Dev-only keys. Never reuse outside localhost; prod reads everything from env in runtime.exs.
config :bullet, Bullet.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key: Base.decode64!("r2y2y0mYk7j9o2Wf8m0mK1bq7lW7m3J3cU0cQ6Yb0Kc="),
       iv_length: 12}
  ]

# Real Bunny in dev when credentials are exported; otherwise the offline Fake.
config :bullet,
       :media_provider,
       if(System.get_env("BUNNY_API_KEY"), do: Bullet.Media.Bunny, else: Bullet.Media.Fake)

config :bullet, :secrets,
  cpf_hmac_key: "dev-cpf-hmac-key",
  bunny_library_id: System.get_env("BUNNY_LIBRARY_ID", "0"),
  bunny_api_key: System.get_env("BUNNY_API_KEY", "dev"),
  bunny_embed_token_key: System.get_env("BUNNY_EMBED_TOKEN_KEY", "dev"),
  bunny_webhook_key: System.get_env("BUNNY_READONLY_API_KEY", "dev"),
  bunny_cdn_hostname: System.get_env("BUNNY_CDN_HOSTNAME")

config :bullet, :secure_cookies, false

# E-mail in dev: kept in the local mailbox (http://localhost:4000/dev/mailbox)
# unless RESEND_API_KEY is exported, in which case it is really sent. Without a
# verified domain in Resend, use MAIL_FROM=onboarding@resend.dev (Resend then
# only delivers to the e-mail of the Resend account owner).
if api_key = System.get_env("RESEND_API_KEY") do
  config :bullet, Bullet.Mailer, adapter: Swoosh.Adapters.Resend, api_key: api_key
  config :swoosh, :api_client, Swoosh.ApiClient.Req
  config :bullet, :mail_from, {"bullethub", System.get_env("MAIL_FROM", "onboarding@resend.dev")}
end
