defmodule BulletWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :bullet

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # Admin (LiveView) session only; the SPA uses bearer + refresh cookie.
  @session_options [
    store: :cookie,
    key: "_bh_admin",
    signing_salt: "666nhSnr",
    encryption_salt: "cXg3Hq7w",
    same_site: "Strict",
    http_only: true,
    secure: Application.compile_env(:bullet, :secure_cookies, true)
  ]

  # auth_token is a socket-level option in Phoenix 1.8: set inside `websocket:`
  # it gets overwritten with nil and every connection is refused.
  socket "/socket", BulletWeb.UserSocket,
    auth_token: true,
    websocket: [connect_info: [:peer_data, :x_headers, :user_agent]],
    longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/app/assets",
    from: {:bullet, "priv/static/app/assets"},
    gzip: not code_reloading?,
    headers: %{"cache-control" => "public, max-age=31536000, immutable"}

  # PWA files must live at the root: the service worker's scope is its own path.
  # no-cache (revalidate by ETag) so a new sw.js is picked up on the next visit.
  plug Plug.Static,
    at: "/",
    from: {:bullet, "priv/static/app"},
    only: ~w(manifest.webmanifest sw.js icons),
    headers: %{"cache-control" => "no-cache"}

  # Vite prefixes the manifest/icon links in index.html with its base (/app/).
  plug Plug.Static,
    at: "/app",
    from: {:bullet, "priv/static/app"},
    only: ~w(manifest.webmanifest icons),
    headers: %{"cache-control" => "no-cache"}

  plug Plug.Static,
    at: "/",
    from: :bullet,
    gzip: not code_reloading?,
    only: BulletWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :bullet
  end

  plug BulletWeb.Plugs.RemoteIp
  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 1_000_000,
    body_reader: {BulletWeb.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BulletWeb.Router
end
